Device:
  # EndDevice
  Workstation:
  SmartPhone:

  # IoT
  SmartTV:
  VoiceAssistant:
  Hub:
  Appliance:

  # NetDevice
  Router:
  NAS:
  Server:


OperatingSystem:
  Windows:
    '7':
    '8':
    '8_1':
    '10':
  Linux:
    'Ubuntu':
    'Fedora':
    'CentOS':
    'Debian':
    'openSUSE':
  MacOS:
    '10_11_ElCapitan':
    '10_12_Sierra':
    '10_13_HighSierra':
    '10_14_Mojave':
    '10_15_Catalina':
  iOS:
  Android: